#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Aug 27 14:03:59 2017

@author: chendongcai
"""

import numpy as np
import operator
from pandas import DataFrame 
def knnclassifier(inX,dataset,label,k):
    datasetsize=dataset.shape[0]
    diffmatrix=np.tile(inX,(datasetsize,1))-dataset
    distance=(diffmatrix**2).sum(axis=1)**0.5
    sortdistanceindices=distance.argsort()
    classcount={} 
    #select the k closet points
    for i in range(k):
        votelabel=label[sortdistanceindices[i]]
        classcount[votelabel]=classcount.get(votelabel,0)+1
    sortclasscount=sorted(classcount.items(),key=operator.itemgetter(1),reverse=True)
    return sortclasscount[0][0]
group=np.array([[1.0,1.0],[1.0,1.1],[0,0],[0,0.1]])
label=['A','A','B','B']
k=3
inputx=np.array([[0,0],[0.5,0.5],[1.5,1.1]])
result=DataFrame(inputx)
r=[]
for i in inputx:
   r.append(knnclassifier(i,group,label,k))
result['class']=r
print(result)
        
        
    
